Add Simplified Chinese (China) translation
TranslucentTB/TranslucentTB pull request #498
Opened 2021-11-27 14:07 UTC by SiderealArt

2021-11-28 04:32 UTC, roxk commented on TranslucentTB/resources/language/TranslucentTB.zh-CN.rc2
> +	IDS_WELCOME_NOTIFICATION APP_NAME L" 將隱藏在托盤中。\n\n對托盤圖標點擊右鍵以修改設置、設為開機時啟動、檢視關於資訊、關閉應用...等。"
Still traditional chinese

2021-11-28 04:33 UTC, roxk requested changes
Just need 1 correction.

2021-11-28 05:16 UTC, SiderealArt commented on TranslucentTB/resources/language/TranslucentTB.zh-CN.rc2
> +	IDS_WELCOME_NOTIFICATION APP_NAME L" 將隱藏在托盤中。\n\n對托盤圖標點擊右鍵以修改設置、設為開機時啟動、檢視關於資訊、關閉應用...等。"
Fixed.

2021-11-29 04:41 UTC, TigerCubDen reviewed
A little assistance, thanks for your work : )

2021-11-29 04:41 UTC, TigerCubDen commented on Xaml/Strings/zh-CN/Resources.resw
> +儲存檔案後，TranslucentTB 將自動載入更動</value>
not simplified Chinese

2021-11-29 04:41 UTC, TigerCubDen commented on Xaml/Strings/zh-CN/Resources.resw
> +    <value>压克力</value>
压克力 → 亚克力

2021-11-29 04:41 UTC, TigerCubDen commented on Xaml/Strings/zh-CN/Resources.resw
> +    <value>加入我们的 Discord 伺服器</value>
伺服器 → 服务器

2021-11-29 04:41 UTC, TigerCubDen commented on Xaml/Strings/zh-CN/Resources.resw
> +    <value>透过 Liberapay 赞助此专案</value>
透过 → 通过

2021-11-29 04:41 UTC, TigerCubDen commented on Xaml/Strings/zh-CN/Resources.resw
> +    <value>开启搜寻菜单时</value>
搜寻 → 搜索

2021-11-29 04:41 UTC, TigerCubDen commented on Xaml/Strings/zh-CN/Resources.resw
> +    <value>侦错</value>
侦错 → 调试

2021-11-29 04:41 UTC, TigerCubDen commented on TranslucentTB/resources/language/TranslucentTB.zh-CN.rc2
> +	IDS_HIDETRAY_DIALOG L"此更动仅暂时生效，下次 "APP_NAME L" 启动时将被还原。 \n\n若要永久更动，请透过 「高级」> 「编辑设置」开启配置文件，并将 ""hide_tray"" 设为 false。 \n\n您确定要继续吗？"
透过 → 通过

2021-11-29 04:41 UTC, TigerCubDen commented on Xaml/Strings/zh-CN/Resources.resw
> +儲存檔案後，TranslucentTB 將自動載入更動</value>
档案 → 文件

2021-11-29 04:41 UTC, TigerCubDen commented on Xaml/Strings/zh-CN/Resources.resw
> +    <value>恢复出厂设置</value>
恢复出厂设置 → 恢复默认设置

2021-11-29 08:56 UTC, SiderealArt commented
All fixed! Thanks for the suggestion, I still got a lot to learn.

2021-12-02 16:10 UTC, sylveon commented
Thanks for the translation again! And thank you to @roxk and @TigerCubDen for double checking!

2021-12-02 16:10 UTC, merged