Add Arabic (Saudi Arabia) translation
TranslucentTB/TranslucentTB pull request #501
Opened 2021-11-28 11:01 UTC by FiberAhmed

**Sorry for the previous pull request but it was messed by mistake, sorry.**

2021-11-28 11:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/TranslucentTB/TranslucentTB?pullRequest=501) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/TranslucentTB/TranslucentTB?pullRequest=501) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/TranslucentTB/TranslucentTB?pullRequest=501) it.</sub>

2021-12-02 16:12 UTC, sylveon commented
Can you sign the CLA please? Also, I've never tried TTB with a RTL language, I'm curious to see how it renders and if there any issues with RTL. Mind sending a few screenshots, maybe?

2021-12-09 19:26 UTC, FiberAhmed commented
> Can you sign the CLA please? Also, I've never tried TTB with a RTL language, I'm curious to see how it renders and if there any issues with RTL. Mind sending a few screenshots, maybe?

I signed CLA

2022-04-15 05:01 UTC, FiberAhmed commented
> Can you sign the CLA please? Also, I've never tried TTB with a RTL language, I'm curious to see how it renders and if there any issues with RTL. Mind sending a few screenshots, maybe?

Now what happened?

2022-08-16 23:54 UTC, Rexogamer commented
They're wondering how the app looks with RTL text

2022-08-17 01:56 UTC, sylveon commented
Yeah, it seems handling RTL is a bit more involved: https://docs.microsoft.com/en-us/windows/apps/design/globalizing/adjust-layout-and-fonts--and-support-rtl#handling-right-to-left-rtl-languages

2022-10-17 10:25 UTC, ahmed605 requested changes

2022-10-17 10:25 UTC, ahmed605 commented on TranslucentTB/resources/language/TranslucentTB.ar-SA.rc2
> +	IDS_WELCOME_NOTIFICATION APP_NAME L" يعيش في علبة النظام.\n\nانقر بزر الماوس الأيمن فوق رمز العلبة لتغيير الإعدادات، وتعيين التطبيق لفتحه عند التمهيد، وعرض المعلومات، والخروج من التطبيق، وما إلى ذلك
I think this should look like this instead
```
IDS_WELCOME_NOTIFICATION L".يعيش في منطقة الإشعارات " APP_NAME L"\n\n.انقر بزر الماوس الأيمن فوق أيقونة الإشعار لتغيير الإعدادات، وتعيين التطبيق لفتحه عند بدء تشغيل النظام، وعرض المعلومات، والخروج من التطبيق، وما إلى ذلك"
```

2022-10-17 10:25 UTC, ahmed605 commented on TranslucentTB/resources/language/TranslucentTB.ar-SA.rc2
> +	IDS_HIDETRAY_DIALOG L"هذا التغيير مؤقت وسيتم فقده في المرة التالية " APP_NAME L" التي يتم فيها البدء. \n\nلجعل هذا الأمر دائمًا، قم بتحرير ملف التكوين باستخدام ""خيارات متقدمة"" > ""تعديل الإعدادات"
`false` should be `true` instead, see: https://github.com/TranslucentTB/TranslucentTB/blob/386ebf11eeeea0666981355474dd64cba70c8e2a/TranslucentTB/resources/language/TranslucentTB.en-US.rc2#L60

Suggested edits:
```
IDS_HIDETRAY_DIALOG APP_NAME L" هذا التغيير مؤقت وسيتم فقده في المرة التالية التي يتم فيها بدء. \n\n.true على hide_tray لجعل هذا الأمر دائمًا، قم بتحرير ملف التكوين باستخدام ""خيارات متقدمة"" > ""تعديل الإعدادات"" واضبط\n\nهل انت متأكد انك تريد المتابعة؟"
```

2022-10-17 10:25 UTC, ahmed605 commented on TranslucentTB/resources/language/TranslucentTB.ar-SA.rc2
> +	IDS_ALREADY_RUNNING APP_NAME L" انه قيد التشغيل بالفعل! انقر بزر الماوس الأيمن على أيقونة العلبة للوصول إليها."
Suggested edits:
```
IDS_ALREADY_RUNNING L".قيد التشغيل بالفعل! انقر بزر الماوس الأيمن على أيقونة الإشعار للوصول إليه " APP_NAME
```

2022-10-17 10:25 UTC, ahmed605 commented on AppPackage/Strings/ar-SA/Resources.resw
> +    <value>مطوِّرو TranslucentTB مفتوح المصدر</value>
Suggested edit:
```xml
    <value>مفتوح المصدر TranslucentTB مطوِّرو</value>
```

2022-10-17 10:25 UTC, ahmed605 commented on Xaml/Strings/ar-SA/Resources.resw
> +    <value>دائما في القمة</value>
Suggested edit:
```xml
    <value>دائما في المقدمة</value>
```

2022-10-17 10:25 UTC, ahmed605 commented on Xaml/Strings/ar-SA/Resources.resw
> +    <value>حول TranslucentTB</value>
Suggested edit:
```xml
    <value>TranslucentTB حول</value>
```

2022-10-17 10:25 UTC, ahmed605 commented on Xaml/Strings/ar-SA/Resources.resw
> +    <value>إخفاء أيقونة العلبة</value>
Suggested edit:
```xml
    <value>إخفاء أيقونة الإشعار</value>
```

2022-10-17 10:25 UTC, ahmed605 commented on Xaml/Strings/ar-SA/Resources.resw
> +يتم إعادة تحميل التغييرات تلقائيًا عند حفظ الملف</value>
Suggested edit:
```xml
    <value>تحرير الإعدادات" في قائمة سياق رمز الإشعار" &gt; "يمكنك دائمًا القيام بذلك عن طريق النقر فوق "خيارات متقدمة
يتم إعادة تحميل التغييرات تلقائيًا عند حفظ الملف</value>
```

2022-10-17 10:25 UTC, ahmed605 commented on Xaml/Strings/ar-SA/Resources.resw
> +    <value>تبرع لمشروع ليبرا باي</value>
Suggested edit:
```xml
    <value>تبرع للمشروع على ليبرا باي</value>
```

2022-10-17 10:25 UTC, ahmed605 commented on Xaml/Strings/ar-SA/Resources.resw
> +    <value>إفتح مُشكلة GitHub</value>
Suggested edit:
```xml
    <value>GitHub فتح طلب على</value>
```

2022-10-17 10:25 UTC, ahmed605 commented on Xaml/Strings/ar-SA/Resources.resw
> +    <value>شكرًا لِتجربة TranslucentTB! بعد النقر على "مُتابعة"، يمكنك تخصيص شكل شريط المهام وفقًا لرغباتك. نأمل أن تستمتع بها، ولا تتردد في ذلك</value>
Suggested edit:
```xml
    <value>بعد النقر على "مُتابعة"، يمكنك تخصيص شكل شريط المهام وفقًا لرغباتك. نأمل أن تستمتع بهذا، ولا تتردد في !TranslucentTB شكرًا لِتجربة</value>
```

2023-07-03 09:34 UTC, littlewhitecloud commented on AppPackage/Strings/ar-SA/Resources.resw
> +    <value>مطوِّرو TranslucentTB مفتوح المصدر</value>
@ahmed605 you can write "```suggestion```" to make a suggestion sush as:
![image](https://github.com/TranslucentTB/TranslucentTB/assets/71159641/56d12ed3-2a9d-4c71-9a56-34ce85df7c1d)

```suggestion
    <value>مفتوح المصدر TranslucentTB مطوِّرو</value>
```

2023-07-03 09:35 UTC, littlewhitecloud commented on TranslucentTB/resources/language/TranslucentTB.ar-SA.rc2
> +	IDS_ALREADY_RUNNING APP_NAME L" انه قيد التشغيل بالفعل! انقر بزر الماوس الأيمن على أيقونة العلبة للوصول إليها."
```suggestion
	IDS_ALREADY_RUNNING L".قيد التشغيل بالفعل! انقر بزر الماوس الأيمن على أيقونة الإشعار للوصول إليه " APP_NAME
```

2023-07-03 09:35 UTC, littlewhitecloud commented on Xaml/Strings/ar-SA/Resources.resw
> +    <value>دائما في القمة</value>
```suggestion
    <value>دائما في المقدمة</value>
```

2023-07-03 09:36 UTC, littlewhitecloud commented on Xaml/Strings/ar-SA/Resources.resw
> +    <value>حول TranslucentTB</value>
```suggestion
    <value>TranslucentTB حول</value>
```

2023-07-03 09:40 UTC, littlewhitecloud reviewed
@ahmed605's suggestions.

2023-07-03 09:40 UTC, littlewhitecloud commented on Xaml/Strings/ar-SA/Resources.resw
> +    <value>إخفاء أيقونة العلبة</value>
```suggestion
    <value>إخفاء أيقونة الإشعار</value>
```

2023-07-03 09:40 UTC, littlewhitecloud commented on Xaml/Strings/ar-SA/Resources.resw
> +يتم إعادة تحميل التغييرات تلقائيًا عند حفظ الملف</value>
```suggestion
    <value>تحرير الإعدادات" في قائمة سياق رمز الإشعار" &gt; "يمكنك دائمًا القيام بذلك عن طريق النقر فوق "خيارات متقدمة
يتم إعادة تحميل التغييرات تلقائيًا عند حفظ الملف</value>
```

2023-07-03 09:40 UTC, littlewhitecloud commented on Xaml/Strings/ar-SA/Resources.resw
> +    <value>تبرع لمشروع ليبرا باي</value>
```suggestion
    <value>تبرع للمشروع على ليبرا باي</value>
```

2023-07-03 09:40 UTC, littlewhitecloud commented on Xaml/Strings/ar-SA/Resources.resw
> +    <value>إفتح مُشكلة GitHub</value>
```suggestion
    <value>GitHub فتح طلب على</value>
```

2023-07-03 09:40 UTC, littlewhitecloud commented on Xaml/Strings/ar-SA/Resources.resw
> +    <value>شكرًا لِتجربة TranslucentTB! بعد النقر على "مُتابعة"، يمكنك تخصيص شكل شريط المهام وفقًا لرغباتك. نأمل أن تستمتع بها، ولا تتردد في ذلك</value>
```suggestion
    <value>بعد النقر على "مُتابعة"، يمكنك تخصيص شكل شريط المهام وفقًا لرغباتك. نأمل أن تستمتع بهذا، ولا تتردد في !TranslucentTB شكرًا لِتجربة</value>
```

2023-07-09 20:08 UTC, sylveon commented
Closing as no author reply

2023-07-09 20:08 UTC, closed without merging